[versions]
kotlin = "2.2.20"
kotlinx-io = "0.8.0"
clikt = "4.4.0"
ktor = "3.3.0"
sqldelight = "2.1.0"
lightningkmp = "1.11.0"
kermit-io = "2.0.8"

# test dependencies
test-logback = "1.5.16"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }